const MeteoraAzulImagens = {
    MeteoraImg_15: require('../Img/METEORA/METEORA-AZUL-15.png'), //Imagem principal
    MeteoraImg_2: require('../Img/METEORA/METEORA-AZUL-2.png'),
    MeteoraImg_3: require('../Img/METEORA/METEORA-AZUL-3.png'),
    MeteoraImg_4: require('../Img/METEORA/METEORA-AZUL-4.png'),
    MeteoraImg_5: require('../Img/METEORA/METEORA-AZUL-5.png'),
    MeteoraImg_6: require('../Img/METEORA/METEORA-AZUL-6.png'),
    MeteoraImg_7: require('../Img/METEORA/METEORA-AZUL-7.png'),
    MeteoraImg_8: require('../Img/METEORA/METEORA-AZUL-8.png'),
    MeteoraImg_9: require('../Img/METEORA/METEORA-AZUL-9.png'),
    MeteoraImg_10: require('../Img/METEORA/METEORA-AZUL-10.png'),
    MeteoraImg_11: require('../Img/METEORA/METEORA-AZUL-11.png'),
    MeteoraImg_12: require('../Img/METEORA/METEORA-AZUL-12.png'),
    MeteoraImg_13: require('../Img/METEORA/METEORA-AZUL-13.png'),
    MeteoraImg_14: require('../Img/METEORA/METEORA-AZUL-14.png'),
    MeteoraImg_16: require('../Img/METEORA/METEORA-AZUL-16.png'),
    MeteoraImg_17: require('../Img/METEORA/METEORA-AZUL-17.png'),
    MeteoraImg_18: require('../Img/METEORA/METEORA-AZUL-18.png'),
    MeteoraImg_19: require('../Img/METEORA/METEORA-AZUL-19.png'),
    MeteoraImg_20: require('../Img/METEORA/METEORA-AZUL-20.png'),
    MeteoraImg_21: require('../Img/METEORA/METEORA-AZUL-21.png'),
    MeteoraImg_22: require('../Img/METEORA/METEORA-AZUL-22.png'),
    MeteoraImg_23: require('../Img/METEORA/METEORA-AZUL-23.png'),
    MeteoraImg_24: require('../Img/METEORA/METEORA-AZUL-24.png'),
    MeteoraImg_25: require('../Img/METEORA/METEORA-AZUL-25.png'),
    MeteoraImg_26: require('../Img/METEORA/METEORA-AZUL-26.png'),
    MeteoraImg_27: require('../Img/METEORA/METEORA-AZUL-27.png'),
    MeteoraImg_28: require('../Img/METEORA/METEORA-AZUL-28.png'),
    MeteoraImg_29: require('../Img/METEORA/METEORA-AZUL-29.png'),
    MeteoraImg_30: require('../Img/METEORA/METEORA-AZUL-30.png'),
    MeteoraImg_31: require('../Img/METEORA/METEORA-AZUL-31.png'),
    MeteoraImg_32: require('../Img/METEORA/METEORA-AZUL-32.png'),
    MeteoraImg_33: require('../Img/METEORA/METEORA-AZUL-33.png'),
    MeteoraImg_34: require('../Img/METEORA/METEORA-AZUL-34.png'),
    MeteoraImg_35: require('../Img/METEORA/METEORA-AZUL-35.png'),
    MeteoraImg_36: require('../Img/METEORA/METEORA-AZUL-36.png'),
    MeteoraImg_37: require('../Img/METEORA/METEORA-AZUL-37.png'),
    MeteoraImg_38: require('../Img/METEORA/METEORA-AZUL-38.png'),
    MeteoraImg_39: require('../Img/METEORA/METEORA-AZUL-39.png'),
    MeteoraImg_40: require('../Img/METEORA/METEORA-AZUL-40.png'),
    MeteoraImg_41: require('../Img/METEORA/METEORA-AZUL-41.png'),
    MeteoraImg_42: require('../Img/METEORA/METEORA-AZUL-42.png'),
    MeteoraImg_43: require('../Img/METEORA/METEORA-AZUL-43.png'),
    MeteoraImg_44: require('../Img/METEORA/METEORA-AZUL-44.png'),
    MeteoraImg_45: require('../Img/METEORA/METEORA-AZUL-45.png'),
    MeteoraImg_46: require('../Img/METEORA/METEORA-AZUL-46.png'),
    MeteoraImg_47: require('../Img/METEORA/METEORA-AZUL-47.png'),
    MeteoraImg_48: require('../Img/METEORA/METEORA-AZUL-48.png'),
    MeteoraImg_49: require('../Img/METEORA/METEORA-AZUL-49.png'),
    MeteoraImg_50: require('../Img/METEORA/METEORA-AZUL-50.png'),
    MeteoraImg_51: require('../Img/METEORA/METEORA-AZUL-51.png'),
    MeteoraImg_52: require('../Img/METEORA/METEORA-AZUL-52.png'),
    MeteoraImg_53: require('../Img/METEORA/METEORA-AZUL-53.png'),
    MeteoraImg_54: require('../Img/METEORA/METEORA-AZUL-54.png'),
    MeteoraImg_55: require('../Img/METEORA/METEORA-AZUL-55.png'),
    MeteoraImg_56: require('../Img/METEORA/METEORA-AZUL-56.png'),
    MeteoraImg_57: require('../Img/METEORA/METEORA-AZUL-57.png'),
    MeteoraImg_58: require('../Img/METEORA/METEORA-AZUL-58.png'),
    MeteoraImg_59: require('../Img/METEORA/METEORA-AZUL-59.png'),
    MeteoraImg_60: require('../Img/METEORA/METEORA-AZUL-60.png'),
    MeteoraImg_61: require('../Img/METEORA/METEORA-AZUL-61.png'),
}
const MeteoraImg = [];
for(const chave in MeteoraAzulImagens){
    MeteoraImg.push(MeteoraAzulImagens[chave]);
}
export {MeteoraImg};